/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Stadium.Simulation;

//import app.src.main.java.Stadium.Simulation.Cloakroom;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // Cloakroom a;
        // a.joinQueue(null);
    }
}
